# General Aliases
alias ll='ls -la'
alias mk='mkdir'
alias rd='rm -r'
alias vrc='vim -p ~/.profile ~/.bashrc ~/.bash_profile'
alias .rc='. ~/.bash_profile'
alias cpr='cp -R'
alias o='open .'
alias tch='touch'
alias src='source'
alias opensub='open -a "Sublime Text 2"'
alias supi='sudo pico'
alias suvi='sudo vim'
alias delfil='rm -Rf'
alias srcbash='src ~/.bashrc'

# GIT Aliases
alias gitit='git init'
alias gitchkm='git checkout master && git pull'
alias gitchk='git checkout'
alias gitone='git clone'
alias gitadd='git add'
alias gitadds='git add *'
alias gitadda='git add -A'
alias gitdel='git add . -A'
alias gitcom='git commit -m'
alias gitcomam='git commit -am'
alias gitrem='git remote add origin'
alias gitremrm='git remote rm origin'
alias gitpush+='git push origin +'
alias gitpush='git push origin'
alias gitpushm='git push origin master'
alias gitstat='git status'

# FX GIT Aliases
alias gitchkahs='git checkout ahs && git pull'
alias gitchkanger='git checkout angermanagement && git pull'
alias gitchkboil='git checkout boilerplate && git pull'
alias gitchkbrandx='git checkout brandx && git pull'
alias gitchkglobalnav='git checkout globalnav && git pull'
alias gitchkjan='git checkout janrain && git pull'
alias gitchklouie='git checkout louie && git pull'
alias gitchksoa='git checkout soa && git pull'
alias gitchksoai='git checkout soa-iphone && git pull'
alias gitchksoas='git checkout soasweeps && git pull'
alias gitchksunny='git checkout sunny && git pull'
alias gitchksunnycoors='git checkout sunnycoors && git pull'
alias gitchkleague='git checkout theleague && git pull'
alias gitchkbiased='git checkout totallybiased && git pull'
alias gitchkufconfx='git checkout ufconfx && git pull'
alias gitchkwilfred='git checkout wilfred && git pull'

alias gitpushahs='git push origin ahs'
alias gitpushanger='git push origin angermanagement'
alias gitpushboil='git push origin boilerplate'
alias gitpushbrandx='git push origin brandx'
alias gitpushglobalnav='git push origin globalnav'
alias gitpushjan='git push origin janrain'
alias gitpushlouie='git push origin louie'
alias gitpushsoa='git push origin soa'
alias gitpushsoai='git push origin soa-iphone'
alias gitpush=soas'git push origin soasweeps'
alias gitpushsunny='git push origin sunny'
alias gitpushsunnycoors='git push origin sunnycoors'
alias gitpushleague='git push origin theleague'
alias gitpushbiased='git push origin totallybiased'
alias gitpushufconfx='git push origin ufconfx'
alias gitpushwilfred='git push origin wilfred'

# Folder Aliases
alias home='cd ~/'
alias rt='cd /'
alias dev='cd ~/Dev && ll'
alias mel='cd ~/Dev/Mel && ll'
alias bashprof='cd ~/Dev/Mel/Bash-Profile && ll'
alias sites='cd ~/Sites/ && ll'
alias fxshows='cd ~/Sites/fx-shows && ll'
alias fxshowspub='cd ~/Sites/fx-shows/public && ll'