# General Aliases
alias ll='ls -la'
alias mk='mkdir'
alias rd='rm -r'
alias vrc='vim -p ~/.profile ~/.bashrc ~/.bash_profile'
alias .rc='. ~/.bash_profile'
alias cpr='cp -R'
alias o='open .'
alias tch='touch'
alias src='source'
alias opensub='open -a "Sublime Text 2"'
alias supi='sudo pico'
alias suvi='sudo vim'
alias delfil='rm -Rf'
alias srcbash='src ~/.bashrc'

# GIT Aliases
alias gitit='git init'
alias gitchkm='git checkout master && git pull'
alias gitchk='git checkout'
alias gitone='git clone'
alias gitadd='git add'
alias gitadds='git add *'
alias gitadda='git add -A'
alias gitdel='git add . -A'
alias gitcom='git commit -m'
alias gitcomam='git commit -am'
alias gitrem='git remote add origin'
alias gitremrm='git remote rm origin'
alias gitpush+='git push origin +'
alias gitpush='git push origin'
alias gitpushm='git push origin master'
alias gitstat='git status'

# Folder Aliases
alias home='cd ~/'
alias rt='cd /'
